---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
        app: my-nginx-webapp
        tier: tier-1
spec:
    containers:
        - name: nginx-container
          image: nginx 
          