---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod-scheduler
    labels:
        app: nginx
spec:
    containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 8080
    nodeName: node02
    