---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-resourcelimit-pod
spec:
    containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "100Mi"
          cpu: 0.5
        limits:
          memory: "200Mi"
          cpu: 1