---
apiVersion: v1
kind: Pod
metadata:
    name: mulitcontainer-pod
    labels:
        app: nginx
        tier: tier-1
spec:
    containers:
        - name: nginx-container
          image: nginx
        - name: busybox-container
          image: busybox