---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-memory-resource-constraint
spec:
  limits:
  - default:
      memory: 1Gi
      cpu: 500m
    defaultRequest:
      memory: 1Gi
      cpu: 500m
    max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 500Mi
      cpu: 100m
    type: Container