---
apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: nginx-daemonset
spec:
    template:
      metadata:
        name: nginx-pod
        labels:
          app: tier-1
      spec:
        containers:
        - name: nginx-container
          image: nginx
          ports:
          - containerPort: 8080
    selector:
      matchLabels:
          app: tier-1
