---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: elasticsearch
  namespace: kube-system
spec:
  template:
    metadata:
      name: elasticsearch-pod
      labels:
        purpose: logging
    spec:
      containers:
        - name: elasticsearch-container
          image: registry.k8s.io/fluentd-elasticsearch:1.20
  selector:
    matchLabels:
      purpose: logging