---
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- schedulerName: my-scheduler 
#If you have multiple masters then uncomment below block
# leaderElection:
#   leaderElect: true
#   resourceNamespace: kube-system
#   resourceName: lock-object-my-scheduler