apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myapp-replicaset
    labels:
      app: myapp
      tier: tier-1
spec:
    template:
      metadata:
        name: myapp
        labels:
          app: myapp
          tier: tier-1
      spec:
        containers:
          - name: nginx-controller
            image: nginx
    replicas: 3
    selector: 
       matchLabels:
          tier: tier-1