---
apiVersion: v1
kind: Secret
metadata:
    name: app-secret
data:
    DB_Host: bXlzcWw=      # mysql -> encoded with base64
    DB_User: cm9vdA==      # root -> encoded with base64
    DB_Password: cGFzd3Jk  # paswrd -> encoded with base64

