---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-pod
    labels:
      tier: tier-1
spec:
    containers:
    - name: nginx-container
      image: nginx
      ports:
        containerPort: 8080
      envFrom:
      - secretRef:
          name: app-secret
      # As a single variable
      # env:
      # - name: DB_Password
      #   valueFrom:
      #       SecretKeyRef:
      #          name: app-secret
      #          key: DB_Password
      # As a volume
      # volumes:
      # - name: app-secret-volume
      #   secret:
      #     secretName: app-secret