---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    labels:
        app: mywebapp
        tier: tier-1
spec:
  template:
      metadata:
        name: nginx-pod
        labels:
          app: nginx-app
          tier: tier-1
      spec:
        containers:
            - name: nginx-container
              image: nginx
  replicas: 3
  selector:
      matchLabels:
          app: nginx-app