apiVersion: v1
kind: Service
metadata:
    name: backend-service
spec:
    type: ClusterIP  #Default service type, so even if do not specify that is fine
    ports:
      - targetPort: 80
        port: 80
    selector:
        app: myapp
        type: back-end